name: Build Java
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Printing ls:"
          ls
          echo "Printing pwd:"
          pwd
          cd custom-actions
          ls
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml