name: Build Java Docker
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./src/main/docker/Dockerfile-cached.jvm
          tags: quarkus/getting-started-jvm:v1.0.0