name: "Try environments and artifacts"

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
  
jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - run: |
          mkdir test
          echo "foo" >> test/file.txt
          echo "bar" >> test/file.txt
#       - uses: actions/upload-artifact@v3
#         with:
#           name: "tfplan"
#           path: test/file.txt
#           retention-days: 3
#       - run: rm -rf test/
#       - uses: actions/download-artifact@v3
#         with:
#           name: "tfplan"
#           path: test
#       - run: cat test/file.txt
