name: Guard
on:
  workflow_dispatch:
jobs:
  guard:
    runs-on: ubuntu-20.04
    if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - run: exit 1
  
  work:
    runs-on: ubuntu-20.04
    steps:
      run: echo "Hello"

