name: "Needs matrix"

on:
  push:
  workflow_dispatch:

jobs:
   ReuseableMatrixJobForDeployment:
    strategy:
      matrix:
        layer: [state, foundation, aks]
    uses: ./.github/workflows/reusable-with-matrix.yaml
    with:
      environment: dev
    secrets: 
      FOO: ${{ secrets.FOO }}
#     strategy:
#       max-parallel: 1
#       fail-fast: false
#       matrix:
#         layer:
#           - "state"
#           - "foundation"
#           - "aks"


       
