name: "Needs matrix"

on:
  push:

jobs:
  plan:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        layer:
          - "state"
          - "foundation"
          - "aks"
          - "databases"
          - "playground"
          - "applicationgateway"
    name: job-${{ matrix.layer }}
    steps:
       - uses: actions/checkout@v3
       - run: ls -l ${{ matrix.layer }}
