name: "Needs matrix"

on:
  push:

jobs:
  create-matrix:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        layer:
          - "state"
          - "foundation"
          - "aks"
    name: job-${{ matrix.layer }}
    defaults:
      run:
        working-directory: layers/${{ matrix.layer}}
    steps:
       - uses: actions/checkout@v3
       - run: echo "${{ github }}"
       
