name: Try custom action
on:
  workflow_dispatch:
    inputs:
      environment:
        description: the env
        type: environment
        required: true
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - name: Try custom action
        uses: akanthos/MyCustomAction@input
        with:
          valueToPrint: salami
