name: "Terraform Validation"

on:
  pull_request:
    branches:
      - main
  push:
    paths:
      - modules/**

jobs:
  format:
    name: Validate Terraform code formatting
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.1

      - name: Terraform Format
        run: terraform fmt -check -recursive

  validate:
    name: Validate Terraform configuration
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: modules/${{ matrix.module }}
    strategy:
      fail-fast: false
      matrix:
        module: [ "storageaccount" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
              - name: Setup Terraform

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate -no-color
