# This is a basic workflow to showcase the use of Reusable Workflows

name: Reusable Workflow user

on:
  pull_request:

jobs:
  sticky-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            Release ${{ github.sha }} to <https://pr-${{ github.event.number }}.example.com>
