name: "Matrix tricks"

on:
  push:

jobs:
  tricks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: ["dev", "int", "prd"]
    env:
      ENV: env-is-${{ matrix.env.uppercase }}
    steps:
      - run: |
          echo $ENV
