name: "Matrix tricks"

on:
  push:

jobs:
  tricks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["dev", "int", "prd"]
    env:
      ENV: ${{ (matrix.environment == 'dev' && 'DEV') || ((matrix.environment == 'int' && 'INT') || 'PRD' ) }}
    steps:
      - run: |
          echo $ENV
